// creamos un componente llamado MainWindow que hereda de Window, el cual 
// permite crear las interfaces para las aplicaiones descargables
import { Button } from "std-widgets.slint";
export component MainWindow inherits Window {

    preferred-width: 1000px;
    preferred-height: 700px;
    title: "FastTerm";
    VerticalLayout {
        padding: 10px;
        Text {
            text: "Contenido de tu terminal...";
        }
    }
}
