// creamos un componente llamado MainWindow que hereda de Window, el cual 
// permite crear las interfaces para las aplicaiones descargables
import {
    Button,
    LineEdit,
} from "std-widgets.slint";
import { WriteLine } from "./components/write-line.slint";
import { HistoryCommand } from "./components/history-command.slint";
import { TerminalSection } from "sections/terminal-section.slint";
import { ActionSection } from "sections/action-section.slint";
export component MainWindow {
    callback sendCommadn(string); // callback para enviar los datos a app

    width: 100%;
    height: 100%;
    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            ActionSection { }

            TerminalSection {
                lineCommand(command) => {
                    sendCommadn(command);
                }
            }
        }
    }
}
