import { StyleVars } from "../../styles/styles.slint";
import {
    LineEdit,
    Button,
} from "std-widgets.slint";
import { SendButton } from "send-button.slint";
import { Context } from "../../global/context.slint";
import { PathView } from "path.slint";
import { CustomInputText } from "custom-input-text.slint";
export component WriteLine {
    // traemos la ruta de donde se abre el terminal
    callback HandleSubmit(string); // enviar el texto escrito a terminalsection
    VerticalLayout {
        padding: 5px;
        PathView {
            path: Context.path;
        }

        HorizontalLayout {

            Text {
                vertical-alignment: center;
                width: StyleVars.size-line-indicator;
                color: StyleVars.color-line-indicator;
                text: "=> ";
            }
            // asi se define tipo el id o similar sera 
            // "nombre" := "componente" , son de el nombre funcionara como referencia
            inputCommand := CustomInputText {
                accepted => {
                    root.HandleSubmit(self.text);
                    self.text = ""; // Se limpia a sí mismo
            }
            }

            SendButton {
                HandleClick => {
                    root.HandleSubmit(inputCommand.text);
                    inputCommand.text = "";
                }
            }
        }
    }
}
